# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard.xci
# IP: The module: 'ClockWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard.xci
# IP: The module: 'ClockWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab5/MulticycleCPU/MulticycleCPU.srcs/sources_1/ip/ClockWizard/ClockWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
