# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.cache/wt [current_project]
set_property parent.project_path /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/lyc/Vivado/lab6/inst_rom.coe
read_verilog /home/lyc/Vivado/lab6/FinalLab/FinalLab.srcs/sources_1/imports/new/MIPS_opcode.vh
read_verilog -library xil_defaultlib {
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/ALU.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/ALUControl.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/ControlUnit.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/Counter.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/new/Extend.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/Fibonacci.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/FrequencyDivision.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/InstructionRegister.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/MUX.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/MulticycleCPU.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/ProgramCounter.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/imports/new/Register.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/new/RegisterFile.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/new/VGADisplayUnit.v
  /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/new/Fibonacci_VGA.v
}
read_ip -quiet /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Memory/Memory.xci
set_property used_in_implementation false [get_files -all /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Memory/Memory_ooc.xdc]

read_ip -quiet /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Clocking_Wizard_1/Clocking_Wizard_1.xci
set_property used_in_implementation false [get_files -all /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Clocking_Wizard_1/Clocking_Wizard_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Clocking_Wizard_1/Clocking_Wizard_1.xdc]
set_property used_in_implementation false [get_files -all /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/sources_1/ip/Clocking_Wizard_1/Clocking_Wizard_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/constrs_1/imports/Vivado/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files /home/lyc/Vivado/lab6/Fibonacci_VGA/Fibonacci_VGA.srcs/constrs_1/imports/Vivado/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Fibonacci_VGA -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Fibonacci_VGA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Fibonacci_VGA_utilization_synth.rpt -pb Fibonacci_VGA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
