# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1.xci
# IP: The module: 'ClockingWizard_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1.xci
# IP: The module: 'ClockingWizard_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/lyc/Vivado/lab6/BubbleSort_VGA/BubbleSort_VGA.srcs/sources_1/ip/ClockingWizard_1/ClockingWizard_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
